### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by csenjoyer1337** [AcierP/discord-account-generator#1]
Hi, the script gave me error proxies.txt file doesnt exist. So i made it and put the proxy in it.
Now, it doesnt do anything at all.
Error:
ValueError: Unknown scheme for proxy URL URL('geo.iproyal.com:REDACTED:CENSORED:CENSORED')

**Comment by acierp** [comment]
i’ve just updated the git. Redownload the latest version of the repository and put your iproyal proxy in config.json

**Comment by csenjoyer1337** [comment]
> i’ve just updated the git. Redownload the latest version of the repository and put your iproyal proxy in config.json

Hello, same error :(

**Comment by csenjoyer1337** [comment]
Update:
I put http://geo.iproyal.com instead of geo.iproyal.com well it seemed to work at 1st but after some seconds of waiting, i get httpx.ProxyError: [WinError 10061], what format should i use the proxies? Thanks :D

**Comment by acierp** [comment]
contact me on discord @ Acier#8770 and I can further assist you

**Comment by csenjoyer1337** [comment]
okay, please accept that request
