### ISSUE TITLE
httpx module error

### ISSUE THREAD

**Issue by ghost** [AcierP/discord-account-generator#2]
I get:

File "C:\Users\dandy\OneDrive\Desktop\discord-account-generator-py\generator.py", line 1, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

do I have to install packages?

**Comment by acierp** [comment]
```pip install httpx``` in command prompt

**Comment by ghost** [comment]
average mac user

**Comment by ghost** [comment]
> average mac user

> 4channel

pathetic
